# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/blot/share/Python/neuropype/gui/displaySweepDockWidget.ui'
#
# Created: Tue Apr 23 10:06:44 2013
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_DockWidget(object):
    def setupUi(self, DockWidget):
        DockWidget.setObjectName(_fromUtf8("DockWidget"))
        DockWidget.resize(672, 592)
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.refreshToolButton = QtGui.QToolButton(self.dockWidgetContents)
        self.refreshToolButton.setObjectName(_fromUtf8("refreshToolButton"))
        self.horizontalLayout_4.addWidget(self.refreshToolButton)
        self.nodeLabel = QtGui.QLabel(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nodeLabel.sizePolicy().hasHeightForWidth())
        self.nodeLabel.setSizePolicy(sizePolicy)
        self.nodeLabel.setObjectName(_fromUtf8("nodeLabel"))
        self.horizontalLayout_4.addWidget(self.nodeLabel)
        self.nodeComboBox = QtGui.QComboBox(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nodeComboBox.sizePolicy().hasHeightForWidth())
        self.nodeComboBox.setSizePolicy(sizePolicy)
        self.nodeComboBox.setObjectName(_fromUtf8("nodeComboBox"))
        self.horizontalLayout_4.addWidget(self.nodeComboBox)
        self.sweepLabel = QtGui.QLabel(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sweepLabel.sizePolicy().hasHeightForWidth())
        self.sweepLabel.setSizePolicy(sizePolicy)
        self.sweepLabel.setObjectName(_fromUtf8("sweepLabel"))
        self.horizontalLayout_4.addWidget(self.sweepLabel)
        self.sweepComboBox = QtGui.QComboBox(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sweepComboBox.sizePolicy().hasHeightForWidth())
        self.sweepComboBox.setSizePolicy(sizePolicy)
        self.sweepComboBox.setObjectName(_fromUtf8("sweepComboBox"))
        self.horizontalLayout_4.addWidget(self.sweepComboBox)
        self.okPushButton = QtGui.QPushButton(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.okPushButton.sizePolicy().hasHeightForWidth())
        self.okPushButton.setSizePolicy(sizePolicy)
        self.okPushButton.setMaximumSize(QtCore.QSize(32, 32))
        self.okPushButton.setObjectName(_fromUtf8("okPushButton"))
        self.horizontalLayout_4.addWidget(self.okPushButton)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.line = QtGui.QFrame(self.dockWidgetContents)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_6.addWidget(self.line)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.displayVLayout = QtGui.QVBoxLayout()
        self.displayVLayout.setObjectName(_fromUtf8("displayVLayout"))
        self.MPLFig = MPLQTFig(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.MPLFig.sizePolicy().hasHeightForWidth())
        self.MPLFig.setSizePolicy(sizePolicy)
        self.MPLFig.setObjectName(_fromUtf8("MPLFig"))
        self.displayVLayout.addWidget(self.MPLFig)
        self.MPLNav = MPLQTNav(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MPLNav.sizePolicy().hasHeightForWidth())
        self.MPLNav.setSizePolicy(sizePolicy)
        self.MPLNav.setObjectName(_fromUtf8("MPLNav"))
        self.displayVLayout.addWidget(self.MPLNav)
        self.horizontalLayout_3.addLayout(self.displayVLayout)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.tabWidget = QtGui.QTabWidget(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMaximumSize(QtCore.QSize(240, 150))
        self.tabWidget.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.simplePlotTab = QtGui.QWidget()
        self.simplePlotTab.setObjectName(_fromUtf8("simplePlotTab"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.simplePlotTab)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.sweepNumLabel = QtGui.QLabel(self.simplePlotTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sweepNumLabel.sizePolicy().hasHeightForWidth())
        self.sweepNumLabel.setSizePolicy(sizePolicy)
        self.sweepNumLabel.setMaximumSize(QtCore.QSize(100, 40))
        self.sweepNumLabel.setObjectName(_fromUtf8("sweepNumLabel"))
        self.verticalLayout_8.addWidget(self.sweepNumLabel)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.startButton = QtGui.QPushButton(self.simplePlotTab)
        self.startButton.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startButton.sizePolicy().hasHeightForWidth())
        self.startButton.setSizePolicy(sizePolicy)
        self.startButton.setMaximumSize(QtCore.QSize(24, 30))
        self.startButton.setFocusPolicy(QtCore.Qt.TabFocus)
        self.startButton.setAutoRepeat(True)
        self.startButton.setObjectName(_fromUtf8("startButton"))
        self.horizontalLayout_7.addWidget(self.startButton)
        self.prev10Button = QtGui.QPushButton(self.simplePlotTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prev10Button.sizePolicy().hasHeightForWidth())
        self.prev10Button.setSizePolicy(sizePolicy)
        self.prev10Button.setMaximumSize(QtCore.QSize(27, 30))
        self.prev10Button.setFocusPolicy(QtCore.Qt.TabFocus)
        self.prev10Button.setAutoRepeat(True)
        self.prev10Button.setObjectName(_fromUtf8("prev10Button"))
        self.horizontalLayout_7.addWidget(self.prev10Button)
        self.prevButton = QtGui.QPushButton(self.simplePlotTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prevButton.sizePolicy().hasHeightForWidth())
        self.prevButton.setSizePolicy(sizePolicy)
        self.prevButton.setMaximumSize(QtCore.QSize(24, 30))
        self.prevButton.setFocusPolicy(QtCore.Qt.TabFocus)
        self.prevButton.setAutoRepeat(True)
        self.prevButton.setObjectName(_fromUtf8("prevButton"))
        self.horizontalLayout_7.addWidget(self.prevButton)
        self.NumSpinBox = QtGui.QSpinBox(self.simplePlotTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.NumSpinBox.sizePolicy().hasHeightForWidth())
        self.NumSpinBox.setSizePolicy(sizePolicy)
        self.NumSpinBox.setMinimumSize(QtCore.QSize(50, 20))
        self.NumSpinBox.setMaximumSize(QtCore.QSize(80, 30))
        self.NumSpinBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.NumSpinBox.setCorrectionMode(QtGui.QAbstractSpinBox.CorrectToNearestValue)
        self.NumSpinBox.setKeyboardTracking(False)
        self.NumSpinBox.setObjectName(_fromUtf8("NumSpinBox"))
        self.horizontalLayout_7.addWidget(self.NumSpinBox)
        self.nextButton = QtGui.QPushButton(self.simplePlotTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nextButton.sizePolicy().hasHeightForWidth())
        self.nextButton.setSizePolicy(sizePolicy)
        self.nextButton.setMaximumSize(QtCore.QSize(24, 30))
        self.nextButton.setFocusPolicy(QtCore.Qt.TabFocus)
        self.nextButton.setAutoRepeat(True)
        self.nextButton.setObjectName(_fromUtf8("nextButton"))
        self.horizontalLayout_7.addWidget(self.nextButton)
        self.next10Button = QtGui.QPushButton(self.simplePlotTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.next10Button.sizePolicy().hasHeightForWidth())
        self.next10Button.setSizePolicy(sizePolicy)
        self.next10Button.setMaximumSize(QtCore.QSize(27, 30))
        self.next10Button.setFocusPolicy(QtCore.Qt.TabFocus)
        self.next10Button.setAutoRepeat(True)
        self.next10Button.setObjectName(_fromUtf8("next10Button"))
        self.horizontalLayout_7.addWidget(self.next10Button)
        self.endButton = QtGui.QPushButton(self.simplePlotTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.endButton.sizePolicy().hasHeightForWidth())
        self.endButton.setSizePolicy(sizePolicy)
        self.endButton.setMaximumSize(QtCore.QSize(24, 30))
        self.endButton.setFocusPolicy(QtCore.Qt.TabFocus)
        self.endButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.endButton.setAutoRepeat(True)
        self.endButton.setObjectName(_fromUtf8("endButton"))
        self.horizontalLayout_7.addWidget(self.endButton)
        self.verticalLayout_8.addLayout(self.horizontalLayout_7)
        spacerItem1 = QtGui.QSpacerItem(20, 38, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem1)
        self.tabWidget.addTab(self.simplePlotTab, _fromUtf8(""))
        self.multiplotTab = QtGui.QWidget()
        self.multiplotTab.setObjectName(_fromUtf8("multiplotTab"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.multiplotTab)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.numSweepLabel = QtGui.QLabel(self.multiplotTab)
        self.numSweepLabel.setObjectName(_fromUtf8("numSweepLabel"))
        self.horizontalLayout_5.addWidget(self.numSweepLabel)
        self.numSweepSpinBox = QtGui.QSpinBox(self.multiplotTab)
        self.numSweepSpinBox.setMinimum(1)
        self.numSweepSpinBox.setMaximum(9999)
        self.numSweepSpinBox.setProperty("value", 10)
        self.numSweepSpinBox.setObjectName(_fromUtf8("numSweepSpinBox"))
        self.horizontalLayout_5.addWidget(self.numSweepSpinBox)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.subMeanCheckBox = QtGui.QCheckBox(self.multiplotTab)
        self.subMeanCheckBox.setObjectName(_fromUtf8("subMeanCheckBox"))
        self.verticalLayout.addWidget(self.subMeanCheckBox)
        self.randomCheckBox = QtGui.QCheckBox(self.multiplotTab)
        self.randomCheckBox.setObjectName(_fromUtf8("randomCheckBox"))
        self.verticalLayout.addWidget(self.randomCheckBox)
        self.xjitterCheckBox = QtGui.QCheckBox(self.multiplotTab)
        self.xjitterCheckBox.setObjectName(_fromUtf8("xjitterCheckBox"))
        self.verticalLayout.addWidget(self.xjitterCheckBox)
        self.horizontalLayout_6.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.rangePushButton = QtGui.QPushButton(self.multiplotTab)
        self.rangePushButton.setMaximumSize(QtCore.QSize(51, 25))
        self.rangePushButton.setObjectName(_fromUtf8("rangePushButton"))
        self.verticalLayout_3.addWidget(self.rangePushButton)
        self.optionsPushButton = QtGui.QPushButton(self.multiplotTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.optionsPushButton.sizePolicy().hasHeightForWidth())
        self.optionsPushButton.setSizePolicy(sizePolicy)
        self.optionsPushButton.setMaximumSize(QtCore.QSize(51, 25))
        self.optionsPushButton.setObjectName(_fromUtf8("optionsPushButton"))
        self.verticalLayout_3.addWidget(self.optionsPushButton)
        self.pltPushButton = QtGui.QPushButton(self.multiplotTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pltPushButton.sizePolicy().hasHeightForWidth())
        self.pltPushButton.setSizePolicy(sizePolicy)
        self.pltPushButton.setMaximumSize(QtCore.QSize(51, 25))
        self.pltPushButton.setObjectName(_fromUtf8("pltPushButton"))
        self.verticalLayout_3.addWidget(self.pltPushButton)
        self.replotPushButton = QtGui.QPushButton(self.multiplotTab)
        self.replotPushButton.setMaximumSize(QtCore.QSize(51, 25))
        self.replotPushButton.setObjectName(_fromUtf8("replotPushButton"))
        self.verticalLayout_3.addWidget(self.replotPushButton)
        self.horizontalLayout_6.addLayout(self.verticalLayout_3)
        self.verticalLayout_7.addLayout(self.horizontalLayout_6)
        spacerItem2 = QtGui.QSpacerItem(20, 18, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem2)
        self.tabWidget.addTab(self.multiplotTab, _fromUtf8(""))
        self.verticalLayout_5.addWidget(self.tabWidget)
        self.scrollArea = QtGui.QScrollArea(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaVBoxLayout = QtGui.QWidget()
        self.scrollAreaVBoxLayout.setGeometry(QtCore.QRect(0, 0, 249, 237))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaVBoxLayout.sizePolicy().hasHeightForWidth())
        self.scrollAreaVBoxLayout.setSizePolicy(sizePolicy)
        self.scrollAreaVBoxLayout.setObjectName(_fromUtf8("scrollAreaVBoxLayout"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.scrollAreaVBoxLayout)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.labelHLayout = QtGui.QHBoxLayout()
        self.labelHLayout.setObjectName(_fromUtf8("labelHLayout"))
        self.chanLabel = QtGui.QLabel(self.scrollAreaVBoxLayout)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chanLabel.sizePolicy().hasHeightForWidth())
        self.chanLabel.setSizePolicy(sizePolicy)
        self.chanLabel.setObjectName(_fromUtf8("chanLabel"))
        self.labelHLayout.addWidget(self.chanLabel)
        self.showLabel = QtGui.QLabel(self.scrollAreaVBoxLayout)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.showLabel.sizePolicy().hasHeightForWidth())
        self.showLabel.setSizePolicy(sizePolicy)
        self.showLabel.setObjectName(_fromUtf8("showLabel"))
        self.labelHLayout.addWidget(self.showLabel)
        self.manLabel = QtGui.QLabel(self.scrollAreaVBoxLayout)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.manLabel.sizePolicy().hasHeightForWidth())
        self.manLabel.setSizePolicy(sizePolicy)
        self.manLabel.setObjectName(_fromUtf8("manLabel"))
        self.labelHLayout.addWidget(self.manLabel)
        self.autoLabel = QtGui.QLabel(self.scrollAreaVBoxLayout)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.autoLabel.sizePolicy().hasHeightForWidth())
        self.autoLabel.setSizePolicy(sizePolicy)
        self.autoLabel.setObjectName(_fromUtf8("autoLabel"))
        self.labelHLayout.addWidget(self.autoLabel)
        self.fullLabell = QtGui.QLabel(self.scrollAreaVBoxLayout)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fullLabell.sizePolicy().hasHeightForWidth())
        self.fullLabell.setSizePolicy(sizePolicy)
        self.fullLabell.setObjectName(_fromUtf8("fullLabell"))
        self.labelHLayout.addWidget(self.fullLabell)
        self.verticalLayout_4.addLayout(self.labelHLayout)
        self.headerLine = QtGui.QFrame(self.scrollAreaVBoxLayout)
        self.headerLine.setFrameShape(QtGui.QFrame.HLine)
        self.headerLine.setFrameShadow(QtGui.QFrame.Sunken)
        self.headerLine.setObjectName(_fromUtf8("headerLine"))
        self.verticalLayout_4.addWidget(self.headerLine)
        self.chanVBoxLayout = QtGui.QVBoxLayout()
        self.chanVBoxLayout.setObjectName(_fromUtf8("chanVBoxLayout"))
        self.verticalLayout_4.addLayout(self.chanVBoxLayout)
        spacerItem3 = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem3)
        self.scrollArea.setWidget(self.scrollAreaVBoxLayout)
        self.verticalLayout_5.addWidget(self.scrollArea)
        self.groupBox = QtGui.QGroupBox(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.xscaleCheckBox = QtGui.QCheckBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xscaleCheckBox.sizePolicy().hasHeightForWidth())
        self.xscaleCheckBox.setSizePolicy(sizePolicy)
        self.xscaleCheckBox.setChecked(True)
        self.xscaleCheckBox.setObjectName(_fromUtf8("xscaleCheckBox"))
        self.horizontalLayout.addWidget(self.xscaleCheckBox)
        self.line_2 = QtGui.QFrame(self.groupBox)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.horizontalLayout.addWidget(self.line_2)
        spacerItem4 = QtGui.QSpacerItem(13, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.xUnitLabel = QtGui.QLabel(self.groupBox)
        self.xUnitLabel.setObjectName(_fromUtf8("xUnitLabel"))
        self.horizontalLayout.addWidget(self.xUnitLabel)
        self.xUnitComboBox = QtGui.QComboBox(self.groupBox)
        self.xUnitComboBox.setObjectName(_fromUtf8("xUnitComboBox"))
        self.horizontalLayout.addWidget(self.xUnitComboBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.xminLabel = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xminLabel.sizePolicy().hasHeightForWidth())
        self.xminLabel.setSizePolicy(sizePolicy)
        self.xminLabel.setMaximumSize(QtCore.QSize(50, 16777215))
        self.xminLabel.setObjectName(_fromUtf8("xminLabel"))
        self.horizontalLayout_2.addWidget(self.xminLabel)
        self.xminDoubleSpinBox = QtGui.QDoubleSpinBox(self.groupBox)
        self.xminDoubleSpinBox.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xminDoubleSpinBox.sizePolicy().hasHeightForWidth())
        self.xminDoubleSpinBox.setSizePolicy(sizePolicy)
        self.xminDoubleSpinBox.setMaximumSize(QtCore.QSize(100, 16777215))
        self.xminDoubleSpinBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.xminDoubleSpinBox.setDecimals(4)
        self.xminDoubleSpinBox.setSingleStep(0.01)
        self.xminDoubleSpinBox.setObjectName(_fromUtf8("xminDoubleSpinBox"))
        self.horizontalLayout_2.addWidget(self.xminDoubleSpinBox)
        self.xmaxLabel = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xmaxLabel.sizePolicy().hasHeightForWidth())
        self.xmaxLabel.setSizePolicy(sizePolicy)
        self.xmaxLabel.setMaximumSize(QtCore.QSize(50, 16777215))
        self.xmaxLabel.setObjectName(_fromUtf8("xmaxLabel"))
        self.horizontalLayout_2.addWidget(self.xmaxLabel)
        self.xmaxDoubleSpinBox = QtGui.QDoubleSpinBox(self.groupBox)
        self.xmaxDoubleSpinBox.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xmaxDoubleSpinBox.sizePolicy().hasHeightForWidth())
        self.xmaxDoubleSpinBox.setSizePolicy(sizePolicy)
        self.xmaxDoubleSpinBox.setMaximumSize(QtCore.QSize(100, 16777215))
        self.xmaxDoubleSpinBox.setDecimals(4)
        self.xmaxDoubleSpinBox.setSingleStep(0.001)
        self.xmaxDoubleSpinBox.setObjectName(_fromUtf8("xmaxDoubleSpinBox"))
        self.horizontalLayout_2.addWidget(self.xmaxDoubleSpinBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout_5.addWidget(self.groupBox)
        self.horizontalLayout_3.addLayout(self.verticalLayout_5)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        DockWidget.setWidget(self.dockWidgetContents)

        self.retranslateUi(DockWidget)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(DockWidget)
        DockWidget.setTabOrder(self.nodeComboBox, self.sweepComboBox)
        DockWidget.setTabOrder(self.sweepComboBox, self.okPushButton)
        DockWidget.setTabOrder(self.okPushButton, self.tabWidget)
        DockWidget.setTabOrder(self.tabWidget, self.startButton)
        DockWidget.setTabOrder(self.startButton, self.prev10Button)
        DockWidget.setTabOrder(self.prev10Button, self.prevButton)
        DockWidget.setTabOrder(self.prevButton, self.NumSpinBox)
        DockWidget.setTabOrder(self.NumSpinBox, self.nextButton)
        DockWidget.setTabOrder(self.nextButton, self.next10Button)
        DockWidget.setTabOrder(self.next10Button, self.endButton)
        DockWidget.setTabOrder(self.endButton, self.scrollArea)
        DockWidget.setTabOrder(self.scrollArea, self.xscaleCheckBox)
        DockWidget.setTabOrder(self.xscaleCheckBox, self.xUnitComboBox)
        DockWidget.setTabOrder(self.xUnitComboBox, self.xminDoubleSpinBox)
        DockWidget.setTabOrder(self.xminDoubleSpinBox, self.xmaxDoubleSpinBox)
        DockWidget.setTabOrder(self.xmaxDoubleSpinBox, self.xjitterCheckBox)
        DockWidget.setTabOrder(self.xjitterCheckBox, self.replotPushButton)
        DockWidget.setTabOrder(self.replotPushButton, self.pltPushButton)
        DockWidget.setTabOrder(self.pltPushButton, self.randomCheckBox)
        DockWidget.setTabOrder(self.randomCheckBox, self.optionsPushButton)
        DockWidget.setTabOrder(self.optionsPushButton, self.rangePushButton)
        DockWidget.setTabOrder(self.rangePushButton, self.subMeanCheckBox)
        DockWidget.setTabOrder(self.subMeanCheckBox, self.numSweepSpinBox)

    def retranslateUi(self, DockWidget):
        DockWidget.setWindowTitle(QtGui.QApplication.translate("DockWidget", "DockWidget", None, QtGui.QApplication.UnicodeUTF8))
        self.refreshToolButton.setText(QtGui.QApplication.translate("DockWidget", "Refresh", None, QtGui.QApplication.UnicodeUTF8))
        self.nodeLabel.setText(QtGui.QApplication.translate("DockWidget", "Node", None, QtGui.QApplication.UnicodeUTF8))
        self.sweepLabel.setText(QtGui.QApplication.translate("DockWidget", "Sweep", None, QtGui.QApplication.UnicodeUTF8))
        self.okPushButton.setText(QtGui.QApplication.translate("DockWidget", "Ok", None, QtGui.QApplication.UnicodeUTF8))
        self.sweepNumLabel.setText(QtGui.QApplication.translate("DockWidget", "Sweep:", None, QtGui.QApplication.UnicodeUTF8))
        self.startButton.setText(QtGui.QApplication.translate("DockWidget", "|<", None, QtGui.QApplication.UnicodeUTF8))
        self.prev10Button.setText(QtGui.QApplication.translate("DockWidget", "-10", None, QtGui.QApplication.UnicodeUTF8))
        self.prevButton.setText(QtGui.QApplication.translate("DockWidget", "<", None, QtGui.QApplication.UnicodeUTF8))
        self.nextButton.setText(QtGui.QApplication.translate("DockWidget", ">", None, QtGui.QApplication.UnicodeUTF8))
        self.next10Button.setText(QtGui.QApplication.translate("DockWidget", "+10", None, QtGui.QApplication.UnicodeUTF8))
        self.endButton.setText(QtGui.QApplication.translate("DockWidget", ">|", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.simplePlotTab), QtGui.QApplication.translate("DockWidget", "Simple plot", None, QtGui.QApplication.UnicodeUTF8))
        self.numSweepLabel.setText(QtGui.QApplication.translate("DockWidget", "# of sweeps:", None, QtGui.QApplication.UnicodeUTF8))
        self.subMeanCheckBox.setText(QtGui.QApplication.translate("DockWidget", "substract mean", None, QtGui.QApplication.UnicodeUTF8))
        self.randomCheckBox.setToolTip(QtGui.QApplication.translate("DockWidget", "If checked, select randomly the sweeps in sweep_list\n"
"Otherwise take the firsts", None, QtGui.QApplication.UnicodeUTF8))
        self.randomCheckBox.setText(QtGui.QApplication.translate("DockWidget", "random", None, QtGui.QApplication.UnicodeUTF8))
        self.xjitterCheckBox.setText(QtGui.QApplication.translate("DockWidget", "x jitter", None, QtGui.QApplication.UnicodeUTF8))
        self.rangePushButton.setText(QtGui.QApplication.translate("DockWidget", "Range", None, QtGui.QApplication.UnicodeUTF8))
        self.optionsPushButton.setText(QtGui.QApplication.translate("DockWidget", "Options", None, QtGui.QApplication.UnicodeUTF8))
        self.pltPushButton.setText(QtGui.QApplication.translate("DockWidget", "Plot!", None, QtGui.QApplication.UnicodeUTF8))
        self.replotPushButton.setToolTip(QtGui.QApplication.translate("DockWidget", "plot the same sweeps as previous call of Plot!", None, QtGui.QApplication.UnicodeUTF8))
        self.replotPushButton.setText(QtGui.QApplication.translate("DockWidget", "replot", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.multiplotTab), QtGui.QApplication.translate("DockWidget", "Multiplot", None, QtGui.QApplication.UnicodeUTF8))
        self.chanLabel.setText(QtGui.QApplication.translate("DockWidget", "Chan", None, QtGui.QApplication.UnicodeUTF8))
        self.showLabel.setText(QtGui.QApplication.translate("DockWidget", "Show", None, QtGui.QApplication.UnicodeUTF8))
        self.manLabel.setText(QtGui.QApplication.translate("DockWidget", "Man", None, QtGui.QApplication.UnicodeUTF8))
        self.autoLabel.setText(QtGui.QApplication.translate("DockWidget", "Auto", None, QtGui.QApplication.UnicodeUTF8))
        self.fullLabell.setText(QtGui.QApplication.translate("DockWidget", "Full", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("DockWidget", "x scale:", None, QtGui.QApplication.UnicodeUTF8))
        self.xscaleCheckBox.setText(QtGui.QApplication.translate("DockWidget", "Auto", None, QtGui.QApplication.UnicodeUTF8))
        self.xUnitLabel.setText(QtGui.QApplication.translate("DockWidget", "x units:", None, QtGui.QApplication.UnicodeUTF8))
        self.xminLabel.setText(QtGui.QApplication.translate("DockWidget", "min:", None, QtGui.QApplication.UnicodeUTF8))
        self.xmaxLabel.setText(QtGui.QApplication.translate("DockWidget", "max:", None, QtGui.QApplication.UnicodeUTF8))

from neuropype.gui.MPLQTclasses import MPLQTFig, MPLQTNav
