# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'share/Python/neuropype/gui/setParamDlg.ui'
#
# Created: Fri Jan  7 17:50:32 2011
#      by: PyQt4 UI code generator 4.7.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_setParamDlg(object):
    def setupUi(self, setParamDlg):
        setParamDlg.setObjectName("setParamDlg")
        setParamDlg.resize(494, 300)
        self.verticalLayout_3 = QtGui.QVBoxLayout(setParamDlg)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.selectNodeLabel = QtGui.QLabel(setParamDlg)
        self.selectNodeLabel.setObjectName("selectNodeLabel")
        self.horizontalLayout.addWidget(self.selectNodeLabel)
        self.selectNodeComboBox = QtGui.QComboBox(setParamDlg)
        self.selectNodeComboBox.setObjectName("selectNodeComboBox")
        self.horizontalLayout.addWidget(self.selectNodeComboBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.line = QtGui.QFrame(setParamDlg)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_3.addWidget(self.line)
        self.scrollArea = QtGui.QScrollArea(setParamDlg)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtGui.QWidget(self.scrollArea)
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 480, 212))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.label_2 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.line_2 = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_2.addWidget(self.line_2)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.line_3 = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_2.addWidget(self.line_3)
        spacerItem1 = QtGui.QSpacerItem(20, 120, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_3.addWidget(self.scrollArea)
        self.line_4 = QtGui.QFrame(setParamDlg)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_3.addWidget(self.line_4)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.closePushButton = QtGui.QPushButton(setParamDlg)
        self.closePushButton.setObjectName("closePushButton")
        self.horizontalLayout_3.addWidget(self.closePushButton)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.defaultPushButton = QtGui.QPushButton(setParamDlg)
        self.defaultPushButton.setObjectName("defaultPushButton")
        self.horizontalLayout_3.addWidget(self.defaultPushButton)
        self.cancelPushButton = QtGui.QPushButton(setParamDlg)
        self.cancelPushButton.setObjectName("cancelPushButton")
        self.horizontalLayout_3.addWidget(self.cancelPushButton)
        self.applyPushButton = QtGui.QPushButton(setParamDlg)
        self.applyPushButton.setObjectName("applyPushButton")
        self.horizontalLayout_3.addWidget(self.applyPushButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.selectNodeLabel.setBuddy(self.selectNodeComboBox)

        self.retranslateUi(setParamDlg)
        QtCore.QMetaObject.connectSlotsByName(setParamDlg)

    def retranslateUi(self, setParamDlg):
        setParamDlg.setWindowTitle(QtGui.QApplication.translate("setParamDlg", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.selectNodeLabel.setText(QtGui.QApplication.translate("setParamDlg", "&node:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("setParamDlg", "Param name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("setParamDlg", "Value", None, QtGui.QApplication.UnicodeUTF8))
        self.closePushButton.setToolTip(QtGui.QApplication.translate("setParamDlg", "Close set param dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.closePushButton.setText(QtGui.QApplication.translate("setParamDlg", "Cl&ose", None, QtGui.QApplication.UnicodeUTF8))
        self.defaultPushButton.setToolTip(QtGui.QApplication.translate("setParamDlg", "Set parameters value to default values", None, QtGui.QApplication.UnicodeUTF8))
        self.defaultPushButton.setText(QtGui.QApplication.translate("setParamDlg", "&Default", None, QtGui.QApplication.UnicodeUTF8))
        self.cancelPushButton.setToolTip(QtGui.QApplication.translate("setParamDlg", "Cancel non applied changes", None, QtGui.QApplication.UnicodeUTF8))
        self.cancelPushButton.setText(QtGui.QApplication.translate("setParamDlg", "&Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.applyPushButton.setToolTip(QtGui.QApplication.translate("setParamDlg", "Apply changes", None, QtGui.QApplication.UnicodeUTF8))
        self.applyPushButton.setText(QtGui.QApplication.translate("setParamDlg", "&Apply", None, QtGui.QApplication.UnicodeUTF8))

