# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'setRangeDlg.ui'
#
# Created: Mon Jan 17 23:31:27 2011
#      by: PyQt4 UI code generator 4.7.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_setRangeDlg(object):
    def setupUi(self, setRangeDlg):
        setRangeDlg.setObjectName("setRangeDlg")
        setRangeDlg.resize(449, 124)
        self.verticalLayout = QtGui.QVBoxLayout(setRangeDlg)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtGui.QLabel(setRangeDlg)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.startSpinBox = QtGui.QSpinBox(setRangeDlg)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startSpinBox.sizePolicy().hasHeightForWidth())
        self.startSpinBox.setSizePolicy(sizePolicy)
        self.startSpinBox.setObjectName("startSpinBox")
        self.horizontalLayout.addWidget(self.startSpinBox)
        self.label_3 = QtGui.QLabel(setRangeDlg)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.endSpinBox = QtGui.QSpinBox(setRangeDlg)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.endSpinBox.sizePolicy().hasHeightForWidth())
        self.endSpinBox.setSizePolicy(sizePolicy)
        self.endSpinBox.setObjectName("endSpinBox")
        self.horizontalLayout.addWidget(self.endSpinBox)
        self.label_4 = QtGui.QLabel(setRangeDlg)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.stepSpinBox = QtGui.QSpinBox(setRangeDlg)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stepSpinBox.sizePolicy().hasHeightForWidth())
        self.stepSpinBox.setSizePolicy(sizePolicy)
        self.stepSpinBox.setMinimum(1)
        self.stepSpinBox.setObjectName("stepSpinBox")
        self.horizontalLayout.addWidget(self.stepSpinBox)
        self.applyPushButton = QtGui.QPushButton(setRangeDlg)
        self.applyPushButton.setObjectName("applyPushButton")
        self.horizontalLayout.addWidget(self.applyPushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.line = QtGui.QFrame(setRangeDlg)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.listIndicesLabel = QtGui.QLabel(setRangeDlg)
        self.listIndicesLabel.setObjectName("listIndicesLabel")
        self.horizontalLayout_2.addWidget(self.listIndicesLabel)
        self.listIndicesLineEdit = QtGui.QLineEdit(setRangeDlg)
        self.listIndicesLineEdit.setObjectName("listIndicesLineEdit")
        self.horizontalLayout_2.addWidget(self.listIndicesLineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.buttonBox = QtGui.QDialogButtonBox(setRangeDlg)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok|QtGui.QDialogButtonBox.RestoreDefaults)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.label_2.setBuddy(self.startSpinBox)
        self.label_3.setBuddy(self.endSpinBox)
        self.label_4.setBuddy(self.stepSpinBox)
        self.listIndicesLabel.setBuddy(self.listIndicesLineEdit)

        self.retranslateUi(setRangeDlg)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), setRangeDlg.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), setRangeDlg.reject)
        QtCore.QMetaObject.connectSlotsByName(setRangeDlg)
        setRangeDlg.setTabOrder(self.startSpinBox, self.endSpinBox)
        setRangeDlg.setTabOrder(self.endSpinBox, self.stepSpinBox)
        setRangeDlg.setTabOrder(self.stepSpinBox, self.applyPushButton)
        setRangeDlg.setTabOrder(self.applyPushButton, self.listIndicesLineEdit)
        setRangeDlg.setTabOrder(self.listIndicesLineEdit, self.buttonBox)

    def retranslateUi(self, setRangeDlg):
        setRangeDlg.setWindowTitle(QtGui.QApplication.translate("setRangeDlg", "Set range", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("setRangeDlg", "&start:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("setRangeDlg", "&end:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("setRangeDlg", "ste&p:", None, QtGui.QApplication.UnicodeUTF8))
        self.applyPushButton.setText(QtGui.QApplication.translate("setRangeDlg", "a&pply", None, QtGui.QApplication.UnicodeUTF8))
        self.listIndicesLabel.setToolTip(QtGui.QApplication.translate("setRangeDlg", "Coma seperated integers.", None, QtGui.QApplication.UnicodeUTF8))
        self.listIndicesLabel.setText(QtGui.QApplication.translate("setRangeDlg", "&list of indices:", None, QtGui.QApplication.UnicodeUTF8))
        self.listIndicesLineEdit.setToolTip(QtGui.QApplication.translate("setRangeDlg", "Coma seperated integers.", None, QtGui.QApplication.UnicodeUTF8))

